### ISSUE TITLE
[FEATURE] v3.2 todo

### ISSUE THREAD

**Issue by 0x4f53** [0x4f53/Wristkey#42]
### Bug fixes
- [ ] Fix splash screen incompatibility bug for Play Store (use official Splash Screen API)
- [ ] Fix a bug where RecyclerView Items flicker and give wrong 2FA codes
- [ ] Disallow file imports by detecting if app is release version
- [ ] Kill app on exit

### Performance improvements
- [ ] Allow option to disable separate data encryption (force user to enable keyguard and disable USB and WiFi debugging first!)
- [ ] Populate app views dynamically instead of at once (shimmer)

### New features
- [ ] Allow sorting options
  - [ ] most used (detect tapped code) 
  - [ ] recently used
  - [ ] alphabetical (ascending and descending)
